In [2]:
import pandas as pd

# Sample data for filmes table
filmes_data = {
    'id_filme': list(range(1, 21)),
    'nome_filme': [
        'The Shawshank Redemption', 'The Godfather', 'The Dark Knight', 'Pulp Fiction', 'Fight Club',
        'Forrest Gump', 'Inception', 'The Matrix', 'The Lord of the Rings: The Fellowship of the Ring', 'The Avengers',
        'Interstellar', 'Gladiator', 'The Silence of the Lambs', 'The Lion King', 'The Departed',
        'Schindler\'s List', 'The Prestige', 'Braveheart', 'Goodfellas', 'Casablanca'
    ],
    'genero_filme': [
        'Drama', 'Crime', 'Action', 'Crime', 'Drama',
        'Drama', 'Action', 'Action', 'Adventure', 'Action',
        'Adventure', 'Action', 'Crime', 'Animation', 'Crime',
        'Biography', 'Mystery', 'Biography', 'Crime', 'Drama'
    ],
    'imdb_link': [
        'https://www.imdb.com/title/tt0111161/', 'https://www.imdb.com/title/tt0068646/', 'https://www.imdb.com/title/tt0468569/', 'https://www.imdb.com/title/tt0110912/', 'https://www.imdb.com/title/tt0137523/',
        'https://www.imdb.com/title/tt0109830/', 'https://www.imdb.com/title/tt1375666/', 'https://www.imdb.com/title/tt0133093/', 'https://www.imdb.com/title/tt0120737/', 'https://www.imdb.com/title/tt0848228/',
        'https://www.imdb.com/title/tt0816692/', 'https://www.imdb.com/title/tt0172495/', 'https://www.imdb.com/title/tt0102926/', 'https://www.imdb.com/title/tt0110357/', 'https://www.imdb.com/title/tt0407887/',
        'https://www.imdb.com/title/tt0211915/', 'https://www.imdb.com/title/tt0482571/', 'https://www.imdb.com/title/tt0112573/', 'https://www.imdb.com/title/tt0099685/', 'https://www.imdb.com/title/tt0034583/'
    ],
    'img_link': [
        'https://www.example.com/image1.jpg', 'https://www.example.com/image2.jpg', 'https://www.example.com/image3.jpg', 'https://www.example.com/image4.jpg', 'https://www.example.com/image5.jpg',
        'https://www.example.com/image6.jpg', 'https://www.example.com/image7.jpg', 'https://www.example.com/image8.jpg', 'https://www.example.com/image9.jpg', 'https://www.example.com/image10.jpg',
        'https://www.example.com/image11.jpg', 'https://www.example.com/image12.jpg', 'https://www.example.com/image13.jpg', 'https://www.example.com/image14.jpg', 'https://www.example.com/image15.jpg',
        'https://www.example.com/image16.jpg', 'https://www.example.com/image17.jpg', 'https://www.example.com/image18.jpg', 'https://www.example.com/image19.jpg', 'https://www.example.com/image20.jpg'
    ],
    'popularidade_filme': [
        9.3, 9.2, 9.0, 8.9, 8.8,
        8.8, 8.7, 8.7, 8.7, 8.6,
        8.6, 8.5, 8.6, 8.5, 8.5,
        8.5, 8.5, 8.3, 8.2, 8.5
    ],
    'duracao_filme': [
        142.0, 175.0, 152.0, 154.0, 139.0,
        142.0, 148.0, 136.0, 178.0, 143.0,
        169.0, 155.0, 118.0, 88.0, 151.0,
        195.0, 130.0, 177.0, 146.0, 102.0
    ],
    'sinopse': [
        'Two imprisoned men bond over several years, finding solace and eventual redemption through acts of common decency.',
        'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
        'When the menace known as The Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
        'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
        'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.',
        'The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other history unfold through the perspective of an Alabama man with an IQ of 75.',
        'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
        'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.',
        'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.',
        'Earth\'s mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.',
        'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
        'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
        'A young F.B.I. cadet must confide in an incarcerated and manipulative killer to receive his help on catching another serial killer who skins his victims.',
        'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.',
        'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.',
        'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
        'After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.',
        'Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England.',
        'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.',
        'A cynical nightclub owner protects an old flame and her husband from Nazis in Morocco.'
    ],
    'diretor_filme': [
        'Frank Darabont', 'Francis Ford Coppola', 'Christopher Nolan', 'Quentin Tarantino', 'David Fincher',
        'Robert Zemeckis', 'Christopher Nolan', 'Lana Wachowski, Lilly Wachowski', 'Peter Jackson', 'Joss Whedon',
        'Christopher Nolan', 'Ridley Scott', 'Jonathan Demme', 'Roger Allers, Rob Minkoff', 'Martin Scorsese',
        'Steven Spielberg', 'Christopher Nolan', 'Mel Gibson', 'Martin Scorsese', 'Michael Curtiz'
    ],
    'ano_lancamento': [
        1994, 1972, 2008, 1994, 1999,
        1994, 2010, 1999, 2001, 2012,
        2014, 2000, 1991, 1994, 2006,
        1993, 2006, 1995, 1990, 1942
    ],
    'nota_filme': [
        9.3, 9.2, 9.0, 8.9, 8.8,
        8.8, 8.7, 8.7, 8.7, 8.6,
         8.6, 8.5, 8.6, 8.5, 8.5,
         8.5, 8.5, 8.3, 8.2, 8.5
    ],
    'produtora_filme': [
        'Columbia Pictures', 'Paramount Pictures', 'Warner Bros.', 'Miramax', '20th Century Fox',
        'Paramount Pictures', 'Warner Bros.', 'Warner Bros.', 'New Line Cinema', 'Marvel Studios',
        'Paramount Pictures', 'DreamWorks', 'Orion Pictures', 'Walt Disney Pictures', 'Warner Bros.',
        'Universal Pictures', 'Touchstone Pictures', 'Paramount Pictures', 'Warner Bros.', 'Warner Bros.'
    ]
}

# Sample data for atores table
atores_data = {
    'id_ator': list(range(1, 41)),
    'nome_ator': [
        'Tim Robbins', 'Morgan Freeman', 'Bob Gunton', 'Marlon Brando', 'Al Pacino',
        'James Caan', 'Robert Duvall', 'Christian Bale', 'Heath Ledger', 'Aaron Eckhart',
        'John Travolta', 'Samuel L. Jackson', 'Bruce Willis', 'Edward Norton', 'Brad Pitt',
        'Helena Bonham Carter', 'Tom Hanks', 'Robin Wright', 'Gary Sinise', 'Leonardo DiCaprio',
        'Hugo Weaving', 'Keanu Reeves', 'Laurence Fishburne', 'Elijah Wood', 'Ian McKellen',
        'Viggo Mortensen', 'Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo', 'Scarlett Johansson',
        'Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain', 'Russell Crowe', 'Joaquin Phoenix',
        'Connie Nielsen', 'Ray Liotta', 'Joe Pesci', 'Humphrey Bogart', 'Ingrid Bergman'
    ]
}

# Sample data for usuarios table
usuarios_data = {
    'id_usuario': list(range(1, 21)),
    'username': [
        'user1', 'user2', 'user3', 'user4', 'user5',
        'user6', 'user7', 'user8', 'user9', 'user10',
        'user11', 'user12', 'user13', 'user14', 'user15',
        'user16', 'user17', 'user18', 'user19', 'user20'
    ]
}

# Sample data for avaliacoes table
avaliacoes_data = {
    'id_avaliacao': list(range(1, 21)),
    'id_usuario': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    'fk_filme_id': list(range(1, 21)),
    'nota_avaliacao': [
        9.0, 8.5, 7.5, 8.0, 9.5,
        6.5, 8.5, 7.0, 9.0, 8.0,
        9.5, 8.0, 7.5, 9.0, 8.5,
        7.0, 9.0, 8.0, 8.5, 7.5
    ]
}

# Sample data for filme_ator table
filme_ator_data = {
    'id_filme': [
        1, 1, 2, 2, 3,
        3, 4, 4, 5, 5,
        6, 6, 7, 7, 8,
        8, 9, 9, 10, 10
    ],
    'id_ator': [
        1, 2, 3, 4, 5,
        6, 7, 8, 9, 10,
        11, 12, 13, 14, 15,
        16, 17, 18, 19, 20
    ]
}

# Sample data for filme_idioma table
filme_idioma_data = {
    'id_filme': list(range(1, 21)),
    'id_idioma': [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
}

# Creating DataFrame for each table
filmes_df = pd.DataFrame(filmes_data)
atores_df = pd.DataFrame(atores_data)
usuarios_df = pd.DataFrame(usuarios_data)
avaliacoes_df = pd.DataFrame(avaliacoes_data)
filme_ator_df = pd.DataFrame(filme_ator_data)
filme_idioma_df = pd.DataFrame(filme_idioma_data)

# Save DataFrames to CSV
filmes_df.to_csv('filmes.csv', index=False)
atores_df.to_csv('atores.csv', index=False)
usuarios_df.to_csv('usuarios.csv', index=False)
avaliacoes_df.to_csv('avaliacoes.csv', index=False)
filme_ator_df.to_csv('filme_ator.csv', index=False)
filme_idioma_df.to_csv('filme_idioma.csv', index=False)